services:
  nginx:
    image: nginx:1.27.2
    depends_on:
      - fixmystreet
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./conf/nginx.conf-docker:/etc/nginx/conf.d/default.conf
      - ./conf/nginx-main.conf:/etc/nginx/nginx.conf
    networks:
      default:
        aliases:
          - nginx.svc
  fixmystreet:
    image: fixmystreet/fixmystreet:stable
    tty: true
    depends_on:
      postgres:
        condition: service_healthy
      memcached:
        condition: service_started
    cgroup: host
    stop_signal: SIGRTMIN+3
    restart: always
    command: ["/var/www/fixmystreet/docker/start-server-tuned"]
    volumes:
      - ./docker/start-server-tuned:/var/www/fixmystreet/docker/start-server-tuned
      - ./conf/general.yml-docker:/var/www/fixmystreet/fixmystreet/conf/general.yml
      - ./perllib/FixMyStreet/App/Controller/Admin/SiteMessage.pm:/var/www/fixmystreet/fixmystreet/perllib/FixMyStreet/App/Controller/Admin/SiteMessage.pm
      - ./perllib/FixMyStreet/App/Controller/Admin/Stats.pm:/var/www/fixmystreet/fixmystreet/perllib/FixMyStreet/App/Controller/Admin/Stats.pm
      - ./perllib/FixMyStreet/Cobrand/Infrasignal.pm:/var/www/fixmystreet/fixmystreet/perllib/FixMyStreet/Cobrand/Infrasignal.pm
      - ./perllib/FixMyStreet/SightEngine.pm:/var/www/fixmystreet/fixmystreet/perllib/FixMyStreet/SightEngine.pm
      - ./perllib/FixMyStreet/App/Model/PhotoSet.pm:/var/www/fixmystreet/fixmystreet/perllib/FixMyStreet/App/Model/PhotoSet.pm
      - ./perllib/FixMyStreet/App/Controller/Report/New.pm:/var/www/fixmystreet/fixmystreet/perllib/FixMyStreet/App/Controller/Report/New.pm
      - ./perllib/FixMyStreet/App/Controller/Report/Update.pm:/var/www/fixmystreet/fixmystreet/perllib/FixMyStreet/App/Controller/Report/Update.pm
      - ./perllib/FixMyStreet/DB/Result/Problem.pm:/var/www/fixmystreet/fixmystreet/perllib/FixMyStreet/DB/Result/Problem.pm
      - ./web/cobrands/infrasignal:/var/www/fixmystreet/fixmystreet/web/cobrands/infrasignal
      - ./templates/web/infrasignal:/var/www/fixmystreet/fixmystreet/templates/web/infrasignal
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - type: tmpfs
        target: /run
        tmpfs:
          size: "104857600"
      - type: tmpfs
        target: /run/lock
        tmpfs:
          size: "104857600"
    environment:
      POSTGRES_PASSWORD: 'password'
      FMS_DB_HOST: 'postgres.svc'
      FMS_DB_PASS: 'fms'
      FMS_DB_NAME: 'infrasignal'
      FMS_DB_USER: 'fms'
      FMS_ROOT: '/var/www/fixmystreet/fixmystreet'
      SUPERUSER_EMAIL: 'superuser@example.org'
      SUPERUSER_PASSWORD: '5up3r53cr3t'
    networks:
      default:
        aliases:
          - fixmystreet.svc
  postgres:
    build:
      dockerfile_inline: |
        FROM postgres:13.11
        RUN localedef -i en_GB -c -f UTF-8 -A /usr/share/locale/locale.alias en_GB.UTF-8
        ENV LANG=en_GB.utf8
    restart: always
    volumes:
      - fixmystreet-pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: 'password'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=512MB"
      - "-c"
      - "effective_cache_size=2GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=128MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_io_concurrency=200"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=100"
    networks:
      default:
        aliases:
          - postgres.svc
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  memcached:
    image: memcached:1.6.32
    restart: always
    command: memcached -m 128 -c 1024 -t 2
    networks:
      default:
        aliases:
          - memcached.svc

volumes:
  fixmystreet-pgdata:
