services:
  setup:
    build:
      context: ..
      dockerfile: docker/Dockerfile-development
    command: docker/setup
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../:/var/www/fixmystreet
      - fixmystreet-local:/var/www/fixmystreet/local
  css_watcher:
    build:
      context: ..
      dockerfile: docker/Dockerfile-development
    command: bin/make_css --watch
    depends_on:
      setup:
        condition: service_completed_successfully
    volumes:
      - ../:/var/www/fixmystreet
      - fixmystreet-local:/var/www/fixmystreet/local
  nginx:
    image: nginx:1.27.2
    depends_on:
      - fixmystreet
    restart: always
    ports:
      - 3000:80
    volumes:
      - ../web:/var/www/fixmystreet/web:ro
      - ../conf/nginx.conf-dev:/etc/nginx/conf.d/default.conf:ro
      - ../conf/nginx-main.conf:/etc/nginx/nginx.conf:ro
    networks:
      default:
        aliases:
          - nginx.svc
  fixmystreet:
    build:
      context: ..
      dockerfile: docker/Dockerfile-development
    command: docker/start-server-tuned
    tty: true
    restart: always
    depends_on:
      setup:
        condition: service_completed_successfully
      db:
        condition: service_healthy
      memcached:
        condition: service_started
    volumes:
      - ../:/var/www/fixmystreet
      - fixmystreet-local:/var/www/fixmystreet/local
    environment:
      POSTGRES_PASSWORD: 'password'
      LANG: "C.UTF-8"
    networks:
      default:
        aliases:
          - fixmystreet.svc
  db:
    build:
      context: ..
      dockerfile: docker/Dockerfile-postgres
    restart: always
    volumes:
      - ../:/var/www/fixmystreet
      - fixmystreet-local:/var/www/fixmystreet/local
      - fixmystreet-pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: 'password'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=512MB"
      - "-c"
      - "effective_cache_size=2GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=128MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_io_concurrency=200"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=100"
    networks:
      default:
        aliases:
          - postgres.svc
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  memcached:
    image: memcached:1.6.32
    restart: always
    command: memcached -m 128 -c 1024 -t 2
    networks:
      default:
        aliases:
          - memcached.svc
  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    networks:
     default:
       aliases:
         - email.svc

volumes:
  fixmystreet-pgdata:
  fixmystreet-local:
